---
title: "20180625_warwick_pond"
author: "Bryan Milstead"
date: "`r format(Sys.time(), '%d %B %Y')`"
output: github_document
---

```{r setup, include=FALSE, echo = FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(here)
library(knitr)

options(stringsAsFactors = FALSE)
```

<!-- 
For field notes and taxa list see: https://github.com/willbmisled/cyanoscope/blob/master/fieldnotes/20180625_warwick_pond.md
-->

## Field Notes
* Who: Stephen Shivers and Bryan
* Where: Warwick Pond (-71.415163, 42.724714)
* When: June 25, 2018
* How:  3 m vertical tow with a 50 `r paste0(expression("\U03BC"), "m")` plankton net.  Sample stored cold overnight then viewed with a inverted microscope.
* General Comments:  Beautiful day on the lake.  Light breeze, partly cloudy, the water was greenish but did not appear to be blooming.  Using the algae torch we saw elevate chlorophyll a (28-38 `r paste0(expression("\U03BC"), "g / l")`) but low phycocyanin (2-3 `r paste0(expression("\U03BC"), "g / l")`).
* Qualitative phytoplankton assessment - relative abundance assessed visually on a 1 - 5 scale with 1 being low abundance (rare).  We found the following taxa:

Taxon                       | Abundance | link
----------------------------|-----------|--------------------------------------------------------------------
Unidentified Small Cells    |     5     | https://www.inaturalist.org/observations/13812624
*Keratella*                 |     5     | https://www.inaturalist.org/observations/13812321
*Aulacoseira*               |     3     | https://www.inaturalist.org/observations/13828760
*Woronichinia*              |     3     | https://www.inaturalist.org/observations/13828870
*Sphaerocystis*             |     2     | https://www.inaturalist.org/observations/13828988
*Euglena*                   |     1     | https://www.inaturalist.org/observations/13829081
*Cosmarium*          |     1     | https://www.inaturalist.org/observations/13829228
Unknown Cyanobacteria       |     1     | https://www.inaturalist.org/observations/13829269
*Lagerheimia*      |     1     | https://www.inaturalist.org/observations/13829324
*Peridinium*                |     1     | https://www.inaturalist.org/observations/13829379
*Fragilaria*                |     1     | https://www.inaturalist.org/observations/13829424
*Asterionella formosa*              |     1     | https://www.inaturalist.org/observations/13829453
Unknown Chlorophyte-4 cells |     1     | https://www.inaturalist.org/observations/13829480
*Cosmarium*                 |     1     | https://www.inaturalist.org/observations/13829513
Unknown 1 spherical cells   |     1     | https://www.inaturalist.org/observations/13829525










